version: 2.1

orbs:
  yarn: artsy/yarn@2.1.1

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - yarn/test
      - yarn/auto-release:
          # The deploy job is the _only_ job that should have access to our npm
          # tokens. We include a context that has our publish credentials
          # explicitly in this step. https://circleci.com/docs/2.0/contexts/
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - yarn/test
