version: 2.1

orbs:
  yarn: artsy/yarn@6.5.0
  auto: artsy/auto@2.2.0

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - yarn/test
      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore:
                - master
          requires:
            - yarn/test
            - yarn/update-cache
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - yarn/test
            - yarn/update-cache
